{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a5efa5b5",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "\n",
      "Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "\n",
      "Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "\n",
      "Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "\n",
      "Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "\n",
      "Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "You probably need to get an updated matplotlibrc file from\n",
      "https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "or from the matplotlib source distribution\n",
      "{'num_workers': 5, 'num_envs_per_worker': 1, 'create_env_on_driver': False, 'rollout_fragment_length': 200, 'batch_mode': 'truncate_episodes', 'gamma': 0.999, 'lr': 5e-05, 'train_batch_size': 30000, 'model': {'_use_default_native_models': False, 'fcnet_hiddens': [256, 256], 'fcnet_activation': 'tanh', 'conv_filters': [[16, [8, 8], 4], [32, [4, 4], 2], [256, [11, 11], 1]], 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': False, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'num_framestacks': 'auto', 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1, 'framestack': True}, 'optimizer': {}, 'horizon': 1500, 'soft_horizon': False, 'no_done_at_end': False, 'env': None, 'observation_space': None, 'action_space': None, 'env_config': {}, 'env_task_fn': None, 'render_env': False, 'record_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'preprocessor_pref': 'deepmind', 'log_level': 'WARN', 'callbacks': <class 'ray.rllib.agents.callbacks.DefaultCallbacks'>, 'ignore_worker_failures': False, 'log_sys_usage': True, 'fake_sampler': False, 'framework': 'torch', 'eager_tracing': False, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'evaluation_interval': None, 'evaluation_num_episodes': 10, 'evaluation_parallel_to_training': False, 'in_evaluation': False, 'evaluation_config': {}, 'evaluation_num_workers': 0, 'custom_eval_function': None, 'sample_async': False, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'compress_observations': False, 'collect_metrics_timeout': 180, 'metrics_smoothing_episodes': 100, 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'min_iter_time_s': 0, 'timesteps_per_iteration': 0, 'seed': None, 'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, '_fake_gpus': False, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, 'custom_resources_per_worker': {}, 'num_cpus_for_driver': 1, 'placement_strategy': 'PACK', 'input': 'sampler', 'input_config': {}, 'actions_in_input_normalized': False, 'input_evaluation': ['is', 'wis'], 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'multiagent': {'policies': {}, 'policy_mapping_fn': None, 'policies_to_train': None, 'observation_fn': None, 'replay_mode': 'independent', 'count_steps_by': 'env_steps'}, 'logger_config': None, 'simple_optimizer': -1, 'monitor': -1, 'use_critic': True, 'use_gae': True, 'lambda': 0.97, 'kl_coeff': 0.2, 'sgd_minibatch_size': 128, 'shuffle_sequences': True, 'num_sgd_iter': 10, 'lr_schedule': None, 'vf_loss_coeff': 1.0, 'entropy_coeff': 0.0, 'entropy_coeff_schedule': None, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'grad_clip': None, 'kl_target': 0.02, 'vf_share_layers': -1}\n",
      "2022-09-21 22:03:37,528\tINFO services.py:1247 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "== Status ==\n",
      "Memory usage on this node: 5.5/31.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 0/6 CPUs, 0/6 GPUs, 0.0/9.6 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)\n",
      "Result logdir: /home/michael/ray_results/singleagent_figure_eight\n",
      "Number of trials: 1/1 (1 PENDING)\n",
      "+-----------------------------+----------+-------+\n",
      "| Trial name                  | status   | loc   |\n",
      "|-----------------------------+----------+-------|\n",
      "| PPO_AccelEnv-v0_27a76_00000 | PENDING  |       |\n",
      "+-----------------------------+----------+-------+\n",
      "\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m or from the matplotlib source distribution\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m 2022-09-21 22:03:40,049\tINFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m or from the matplotlib source distribution\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=10102)\u001b[0m 2022-09-21 22:03:43,386\tWARNING util.py:55 -- Install gputil for GPU system monitoring.\n",
      "2022-09-21 22:03:48,073\tERROR trial_runner.py:773 -- Trial PPO_AccelEnv-v0_27a76_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\", line 729, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py\", line 1564, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::PPO.train()\u001b[39m (pid=10102, ip=192.168.1.76)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 640, in train\n",
      "    raise e\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 629, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py\", line 170, in step\n",
      "    res = next(self.train_exec_impl)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 828, in add_wait_hooks\n",
      "    item = next(it)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=10104, ip=192.168.1.76)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 740, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "    item = next(self.rollout_provider)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "    sample_collector=sample_collector,\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "    policy_id).transform(raw_obs)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "    self.check_shape(observation)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "    observation, self._obs_space)\n",
      "ValueError: ('Observation ({}) outside given space ({})!', array([[0., 0., 0., ..., 0., 0., 0.],\n",
      "       [0., 0., 0., ..., 0., 0., 0.],\n",
      "       [0., 0., 0., ..., 0., 0., 0.],\n",
      "       ...,\n",
      "       [0., 0., 0., ..., 0., 0., 0.],\n",
      "       [0., 0., 0., ..., 0., 0., 0.],\n",
      "       [0., 0., 0., ..., 0., 0., 0.]]), Box(84, 84))\n",
      "2022-09-21 22:03:48,075\tINFO trial_runner.py:1051 -- Trial PPO_AccelEnv-v0_27a76_00000: Attempting to restore trial state from last checkpoint.\n",
      "== Status ==\n",
      "Memory usage on this node: 7.1/31.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 0/6 CPUs, 0/6 GPUs, 0.0/9.6 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)\n",
      "Result logdir: /home/michael/ray_results/singleagent_figure_eight\n",
      "Number of trials: 1/1 (1 PENDING)\n",
      "+-----------------------------+----------+-------+\n",
      "| Trial name                  | status   | loc   |\n",
      "|-----------------------------+----------+-------|\n",
      "| PPO_AccelEnv-v0_27a76_00000 | PENDING  |       |\n",
      "+-----------------------------+----------+-------+\n",
      "Number of errored trials: 1\n",
      "+-----------------------------+--------------+----------------------------------------------------------------------------------------------------------------+\n",
      "| Trial name                  |   # failures | error file                                                                                                     |\n",
      "|-----------------------------+--------------+----------------------------------------------------------------------------------------------------------------|\n",
      "| PPO_AccelEnv-v0_27a76_00000 |            1 | /home/michael/ray_results/singleagent_figure_eight/PPO_AccelEnv-v0_27a76_00000_0_2022-09-21_22-03-38/error.txt |\n",
      "+-----------------------------+--------------+----------------------------------------------------------------------------------------------------------------+\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=10103)\u001b[0m ./michael_files/emission_collection/singleagent_figure_eight_20220921-2203421663815822.0857174-0_emission.csv ./michael_files/emission_collection/\n",
      "\u001b[2m\u001b[36m(pid=10100)\u001b[0m ./michael_files/emission_collection/singleagent_figure_eight_20220921-2203421663815822.048316-0_emission.csv ./michael_files/emission_collection/\n",
      "\u001b[2m\u001b[36m(pid=10104)\u001b[0m ./michael_files/emission_collection/singleagent_figure_eight_20220921-2203421663815822.0397854-0_emission.csv ./michael_files/emission_collection/\n",
      "\u001b[2m\u001b[36m(pid=10101)\u001b[0m ./michael_files/emission_collection/singleagent_figure_eight_20220921-2203421663815822.0540788-0_emission.csv ./michael_files/emission_collection/\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=10099)\u001b[0m ./michael_files/emission_collection/singleagent_figure_eight_20220921-2203421663815822.04833-0_emission.csv ./michael_files/emission_collection/\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10348)\u001b[0m 2022-09-21 22:03:52,151\tINFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10346)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10347)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10344)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10345)\u001b[0m or from the matplotlib source distribution\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key text.latex.preview in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key mathtext.fallback_to_cm in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key savefig.jpeg_quality in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key keymap.all_axes in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key animation.avconv_path in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m Bad key animation.avconv_args in file /home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m You probably need to get an updated matplotlibrc file from\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template\n",
      "\u001b[2m\u001b[36m(pid=10343)\u001b[0m or from the matplotlib source distribution\n",
      "^C\n"
     ]
    }
   ],
   "source": [
    "!python examples/train.py singleagent_figure_eight"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
